name: Send Payload to App (Python)
description: Sends a payload to the specified app endpoint using Python
runs:
  using: 'composite'
  main: 'composite-action.yaml'
inputs:
  app-endpoint:
    description: 'The endpoint to send the payload to'
    required: true
  app-name:
    description: 'The name of the app'
    required: true
outputs:
  none