name: Send Payload to App (Python)
description: Sends a payload to the specified app endpoint using Python
inputs:
  app-endpoint:
    description: 'The endpoint to send the payload to'
    required: true
  app-name:
    description: 'The name of the app'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Get latest release tag
      id: get_latest_release
      uses: actions/github-script@v6
      with:
        script: |
          const latestRelease = await github.repos.getLatestRelease({
            owner: context.repo.owner,
            repo: context.repo.repo
          });
          core.setOutput('tag_name', latestRelease.data.tag_name);

    - name: Run deploy-register.py
      run: |
        ROLLBACK=${{ steps.get_latest_release.outputs.tag_name }} python deploy-register.py
      shell: bash
      env:
        GITHUB_SHA: ${{ github.sha }}
        INPUT_APP_NAME: ${{ inputs.app-name }}
        INPUT_APP_ENDPOINT: ${{ inputs.app-endpoint }}
