name: 'Deploy Register Action'
description: 'An action to deploy register'
inputs:
  example-input:
    description: 'An example input'
    required: true
    default: 'default value'
runs:
  using: actions/setup-python@v5
  main: 'deploy-register.py'
